In [0]:
import pandas as pd

In [0]:
df = pd.read_csv(
    "/Workspace/Users/sameepbhutani99@gmail.com/Drafts/Sample - Superstore.csv",
    encoding="latin1"
)

In [0]:
df.head()

   Row ID        Order ID  Order Date  ... Quantity Discount    Profit
0       1  CA-2016-152156   11/8/2016  ...        2     0.00   41.9136
1       2  CA-2016-152156   11/8/2016  ...        3     0.00  219.5820
2       3  CA-2016-138688   6/12/2016  ...        2     0.00    6.8714
3       4  US-2015-108966  10/11/2015  ...        5     0.45 -383.0310
4       5  US-2015-108966  10/11/2015  ...        2     0.20    2.5164

[5 rows x 21 columns]

In [0]:
df.tail()

      Row ID        Order ID Order Date  ... Quantity Discount   Profit
9989    9990  CA-2014-110422  1/21/2014  ...        3      0.2   4.1028
9990    9991  CA-2017-121258  2/26/2017  ...        2      0.0  15.6332
9991    9992  CA-2017-121258  2/26/2017  ...        2      0.2  19.3932
9992    9993  CA-2017-121258  2/26/2017  ...        4      0.0  13.3200
9993    9994  CA-2017-119914   5/4/2017  ...        2      0.0  72.9480

[5 rows x 21 columns]

In [0]:
df.shape

(9994, 21)

In [0]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [0]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [0]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [0]:
df.fillna("Unknown", inplace=True)

In [0]:
df.drop_duplicates(inplace=True)

In [0]:
df[df["Sales"] > 100]

      Row ID        Order ID  Order Date  ... Quantity Discount    Profit
0          1  CA-2016-152156   11/8/2016  ...        2     0.00   41.9136
1          2  CA-2016-152156   11/8/2016  ...        3     0.00  219.5820
3          4  US-2015-108966  10/11/2015  ...        5     0.45 -383.0310
7          8  CA-2014-115812    6/9/2014  ...        6     0.20   90.7152
9         10  CA-2014-115812    6/9/2014  ...        5     0.00   34.4700
...      ...             ...         ...  ...      ...      ...       ...
9976    9977  US-2016-103674   12/6/2016  ...        2     0.20   31.1980
9979    9980  US-2016-103674   12/6/2016  ...       14     0.20  153.1152
9988    9989  CA-2017-163629  11/17/2017  ...        5     0.00   55.6470
9991    9992  CA-2017-121258   2/26/2017  ...        2     0.20   19.3932
9993    9994  CA-2017-119914    5/4/2017  ...        2     0.00   72.9480

[3765 rows x 21 columns]

In [0]:
df[["Order ID","Customer Name","Sales"]]

            Order ID     Customer Name     Sales
0     CA-2016-152156       Claire Gute  261.9600
1     CA-2016-152156       Claire Gute  731.9400
2     CA-2016-138688   Darrin Van Huff   14.6200
3     US-2015-108966    Sean O'Donnell  957.5775
4     US-2015-108966    Sean O'Donnell   22.3680
...              ...               ...       ...
9989  CA-2014-110422  Tom Boeckenhauer   25.2480
9990  CA-2017-121258       Dave Brooks   91.9600
9991  CA-2017-121258       Dave Brooks  258.5760
9992  CA-2017-121258       Dave Brooks   29.6000
9993  CA-2017-119914      Chris Cortes  243.1600

[9994 rows x 3 columns]

In [0]:
df["total_amount"] = df["Sales"] * df["Quantity"]

In [0]:
df.head()

   Row ID        Order ID  Order Date  ... Discount    Profit total_amount
0       1  CA-2016-152156   11/8/2016  ...     0.00   41.9136     523.9200
1       2  CA-2016-152156   11/8/2016  ...     0.00  219.5820    2195.8200
2       3  CA-2016-138688   6/12/2016  ...     0.00    6.8714      29.2400
3       4  US-2015-108966  10/11/2015  ...     0.45 -383.0310    4787.8875
4       5  US-2015-108966  10/11/2015  ...     0.20    2.5164      44.7360

[5 rows x 22 columns]

In [0]:
df.to_csv(
    "/Workspace/Users/sameepbhutani99@gmail.com/Drafts/cleaned_superstore.csv",
    index=False
)

In [0]:
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!